### ISSUE TITLE
原理请教

### ISSUE THREAD

**Issue by cjhgit** [liaobinbin/fig-to-json#1]
请问你是通过什么工具或者什么资料去分析 fig 文件的格式的，能否指点一下？

**Comment by liaobinbin** [comment]
@cjhgit 

https://github.com/evanw/kiwi

figma的fig文件实际上就是 基于这个kiwi 将json数据编码后得到的二进制文件

加解密的关键实际上就是需要得到figma自己的schema数据或者文件

我好多代码也是从kiwi里面直接copy过来的。

**Comment by liaobinbin** [comment]
关闭问题
